language: ruby
rvm:
  - 2.3.3

  # Future versions
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - |
    bash -c " # Install MariaDB
    sudo bash .travis_mariadb.sh
    "
  - gem update --system

before_script:
  - mysql -e 'create database pharos_test;'

script:
  - bundle exec rspec spec
  - bundle exec rubocop -V
  - bundle exec rubocop -F
  - bundle exec brakeman -z -A

addons:
  code_climate:
    repo_token: f0411fcc65176d10a86774d0c6434f4621fcbfd898a59f385d08dfff0698c7d4
