apiVersion: v1
kind: Pod
metadata:
  name: velum-private
  labels:
    name: velum-private
spec:
  hostNetwork: false
  containers:
  - name: velum-mariadb
    image: library/mariadb:10.0.29
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "salt"
    volumeMounts:
      - mountPath: /var/run/mysqld
        name: mariadb-unix-socket
      - mountPath: /etc/mysql/conf.d
        name: mariadb-config
  volumes:
    - name: mariadb-unix-socket
      hostPath:
        path: ${project_dir}/kubernetes/tmp/mariadb-socket
    - name: mariadb-config
      hostPath:
        path: ${project_dir}/kubernetes/mariadb
