apiVersion: v1
kind: Pod
metadata:
  name: velum-public
  labels:
    name: velum-public
spec:
  hostNetwork: true
  containers:
  - name: salt-master
    image: opensuse/salt-master:boron
    imagePullPolicy: Always
    env:
    - name: MYSQL_UNIX_PORT
      value: /var/run/mysqld/mysqld.sock
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /srv/salt
      name: salt-master
    - mountPath: /srv/pillar
      name: salt-pillar
    - mountPath: /srv/pillar/vars.sls
      name: salt-pillar-vars
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
    - mountPath: /var/run/mysqld
      name: mariadb-unix-socket
  - name: velum-dashboard
    image: opensuse/velum:development
    imagePullPolicy: Always
    env:
    - name: RAILS_ENV
      value: development
    - name: VELUM_SECRETS_DIR
      value: /var/lib/misc/velum-secrets
    - name: RAILS_SERVE_STATIC_FILES
      value: "true"
    - name: VELUM_PORT
      value: "3000"
    - name: VELUM_DB_HOST
      value:
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_DB_SOCKET
      value: /var/run/mysqld/mysqld.sock
    - name: VELUM_SALT_HOST
      value: "127.0.0.1"
    - name: VELUM_SALT_PORT
      value: "8000"
    - name: VELUM_SALT_USER
      value: saltapi
    - name: VELUM_SALT_PASSWORD
      value: saltapi
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
      - mountPath: /var/lib/misc/velum-secrets
        name: velum-secrets
      - mountPath: /var/run/mysqld
        name: mariadb-unix-socket
    command: ["/bin/sh","-c"]
    args: ["bin/init"]
  - name: salt-api
    image: opensuse/salt-api:boron
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-minion-ca
    image: opensuse/salt-minion:boron
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/salt/minion.d/minion.conf
      name: salt-minion-ca-config
    - mountPath: /etc/salt/minion.d/signing_policies.conf
      name: salt-minion-ca-signing-policies
    - mountPath: /etc/salt/grains
      name: salt-minion-ca-grains
  - name: velum-event-processor
    image: opensuse/velum:development
    imagePullPolicy: Always
    env:
    - name: WORKER_ID
      value: Worker_1
    - name: RAILS_ENV
      value: development
    - name: VELUM_SECRETS_DIR
      value: /var/lib/misc/velum-secrets
    - name: VELUM_DB_HOST
      value:
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_DB_SOCKET
      value: /var/run/mysqld/mysqld.sock
    - name: VELUM_SALT_HOST
      value: "127.0.0.1"
    - name: VELUM_SALT_PORT
      value: "8000"
    - name: VELUM_SALT_USER
      value: saltapi
    - name: VELUM_SALT_PASSWORD
      value: saltapi
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
      - mountPath: /var/lib/misc/velum-secrets
        name: velum-secrets
      - mountPath: /var/run/mysqld
        name: mariadb-unix-socket
    command: ["/bin/sh","-c"]
    args: ["bundle exec bin/rake salt:process"]
  volumes:
    - name: velum-source-code
      hostPath:
        path: ${project_dir}
    - name: velum-secrets
      hostPath:
        path: ${project_dir}/kubernetes/tmp/velum-secrets
    - name: mariadb-unix-socket
      hostPath:
        path: ${project_dir}/kubernetes/tmp/mariadb-socket
    - name: salt-master-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/master.d
    - name: salt-master
      hostPath:
        path: ${salt_dir}/salt
    - name: salt-pillar
      hostPath:
        path: ${salt_dir}/pillar
    - name: salt-pillar-vars
      hostPath:
        path: ${project_dir}/kubernetes/salt/pillar/vars.sls
    - name: salt-sock-dir
      hostPath:
        path: ${project_dir}/kubernetes/tmp/salt-sock-dir
    - name: salt-minion-ca-grains
      hostPath:
        path: ${project_dir}/kubernetes/salt/grains/ca
    - name: salt-minion-ca-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/minion.d-ca/minion.conf
    - name: salt-minion-ca-signing-policies
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/minion.d-ca/signing_policies.conf
