apiVersion: v1
kind: Pod
metadata:
  name: salt
  labels:
    name: salt
spec:
  hostNetwork: true
  containers:
  - name: salt-master
    image: opensuse/salt-master:boron
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /srv/salt
      name: salt-master
    - mountPath: /srv/pillar
      name: salt-pillar
    - mountPath: /srv/pillar/vars.sls
      name: salt-pillar-vars
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
    - mountPath: /etc/salt/cloud.providers.d/
      name: salt-cloud-providers
    - mountPath: /pem_keys
      name: salt-cloud-pem-keys
    - mountPath: /usr/lib/python2.7/site-packages/salt/cloud/deploy/
      name: salt-cloud-deploy-scripts
  - name: salt-api
    image: opensuse/salt-api:boron
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-minion-ca
    image: opensuse/salt-minion:boron
    volumeMounts:
    - mountPath: /etc/salt/minion.d/minion.conf
      name: salt-minion-ca-config
    - mountPath: /etc/salt/minion.d/signing_policies.conf
      name: salt-minion-ca-signing-policies
    - mountPath: /etc/salt/grains
      name: salt-minion-ca-grains
  volumes:
    - name: salt-master-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/master.d
    - name: salt-master
      hostPath:
        path: ${salt_dir}/salt
    - name: salt-pillar
      hostPath:
        path: ${salt_dir}/pillar
    - name: salt-pillar-vars
      hostPath:
        path: ${project_dir}/kubernetes/salt/pillar/vars.sls
    - name: salt-sock-dir
      hostPath:
        path: ${project_dir}/kubernetes/tmp/salt-sock-dir
    - name: salt-minion-ca-grains
      hostPath:
        path: ${project_dir}/kubernetes/salt/grains/ca
    - name: salt-minion-ca-config
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/minion.d-ca/minion.conf
    - name: salt-minion-ca-signing-policies
      hostPath:
        path: ${project_dir}/kubernetes/salt/config/minion.d-ca/signing_policies.conf
    - name: salt-cloud-providers
      hostPath:
        path: ${project_dir}/kubernetes/salt/cloud.providers.d/
    - name: salt-cloud-pem-keys
      hostPath:
        path: ${project_dir}/tmp/pem_keys/
    - name: salt-cloud-deploy-scripts
      hostPath:
        path: ${project_dir}/kubernetes/salt/cloud/deploy/
