apiVersion: v1
kind: Pod
metadata:
  name: velum
  labels:
    name: velum
spec:
  hostNetwork: true
  containers:
  - name: velum-dashboard
    image: opensuse/velum:development
    env:
    - name: RAILS_ENV
      value: development
    - name: RAILS_SERVE_STATIC_FILES
      value: "true"
    - name: VELUM_DB_HOST
      value: "127.0.0.1"
    - name: VELUM_DB_PORT
      value: "3306"
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_SALT_HOST
      value: "127.0.0.1"
    - name: VELUM_SALT_PORT
      value: "8000"
    - name: VELUM_SALT_USER
      value: saltapi
    - name: VELUM_SALT_PASSWORD
      value: saltapi
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
    command: ["/bin/sh","-c"]
    args: ["bundle exec rails s -b 0.0.0.0 -p 3000 --pid /tmp/puma.pid Puma"]
  - name: velum-event-processor
    image: opensuse/velum:development
    env:
    - name: WORKER_ID
      value: Worker_1
    - name: RAILS_ENV
      value: development
    - name: VELUM_DB_HOST
      value: "127.0.0.1"
    - name: VELUM_DB_PORT
      value: "3306"
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_SALT_HOST
      value:
    - name: VELUM_SALT_PORT
      value:
    - name: VELUM_SALT_USER
      value:
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
    command: ["/bin/sh","-c"]
    args: ["bundle exec bin/rake salt:process"]
  - name: velum-mariadb
    image: library/mariadb:10.0.29
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "salt"
  volumes:
    - name: velum-source-code
      hostPath:
        path: ${project_dir}
