apiVersion: v1
kind: Pod
metadata:
  name: velum
  labels:
    name: velum
spec:
  hostNetwork: true
  containers:
  - name: velum-dashboard
    image: opensuse/velum:development
    env:
    - name: RAILS_ENV
      value: development
    - name: SECRET_KEY_BASE
      value: fc0ece3811c0b1e0118dd7d619b385955e3ed146b37315d67d1c2d201c42531da398941ef27aab42493fff23afcba540390a26db51b5889e96d850a14178aabdc1926c013936a3c41abdbeb696ce440685c5d7be3a6c548434699d526a9e37657a76a43ca975b824905fd949f7e8d50aa1196a58e7e79dcfb08e2e397ee4f7b7
    - name: RAILS_SERVE_STATIC_FILES
      value: "true"
    - name: VELUM_DB_HOST
      value: "127.0.0.1"
    - name: VELUM_DB_PORT
      value: "3306"
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_SALT_HOST
      value: "127.0.0.1"
    - name: VELUM_SALT_PORT
      value: "8000"
    - name: VELUM_SALT_USER
      value: saltapi
    - name: VELUM_SALT_PASSWORD
      value: saltapi
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
    command: ["/bin/sh","-c"]
    args: ["bundle exec rails s -b 0.0.0.0 -p 3000 --pid /tmp/puma.pid Puma"]
  - name: velum-event-processor
    image: opensuse/velum:development
    env:
    - name: WORKER_ID
      value: Worker_1
    - name: RAILS_ENV
      value: development
    - name: SECRET_KEY_BASE
      value: fc0ece3811c0b1e0118dd7d619b385955e3ed146b37315d67d1c2d201c42531da398941ef27aab42493fff23afcba540390a26db51b5889e96d850a14178aabdc1926c013936a3c41abdbeb696ce440685c5d7be3a6c548434699d526a9e37657a76a43ca975b824905fd949f7e8d50aa1196a58e7e79dcfb08e2e397ee4f7b7
    - name: VELUM_DB_HOST
      value: "127.0.0.1"
    - name: VELUM_DB_PORT
      value: "3306"
    - name: VELUM_DB_USERNAME
      value: "root"
    - name: VELUM_DB_PASSWORD
      value: "salt"
    - name: VELUM_SALT_HOST
      value:
    - name: VELUM_SALT_PORT
      value:
    - name: VELUM_SALT_USER
      value:
    - name: VELUM_KUBERNETES_HOST
      value:
    - name: VELUM_KUBERNETES_PORT
      value:
    - name: VELUM_KUBERNETES_CERT_DIRECTORY
      value:
    volumeMounts:
      - mountPath: /usr/src/app
        name: velum-source-code
    command: ["/bin/sh","-c"]
    args: ["bundle exec bin/rake salt:process"]
  - name: velum-mariadb
    image: library/mariadb:10.0.29
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "salt"
  volumes:
    - name: velum-source-code
      hostPath:
        path: ${project_dir}
